# Generated by Django 5.2.4 on 2026-01-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_article_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('highlight', 'Highlight'), ('case_study', 'Case Study'), ('webinar', 'Webinar'), ('learning', 'Learning'), ('other', 'Other / Future')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/images/')),
                ('image_url', models.URLField(blank=True)),
                ('link', models.URLField(blank=True, help_text='Internal or external link (Pinterest, YouTube, Medium, etc.)')),
                ('is_featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='website.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='website.category'),
        ),
    ]
