# Generated by Django 5.2.4 on 2026-01-20 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_category_alter_article_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/popular/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MagazineIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='magazine/covers/')),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('video_preview_url', models.URLField(blank=True, null=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='website.category')),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
