# Generated by Django 5.2.4 on 2026-07-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_populararticle_magazineissue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
