# Generated by Django 5.2.4 on 2025-11-19 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('material_wanted', models.CharField(choices=[('wood', 'Wood'), ('metal', 'Metal'), ('textiles', 'Textiles'), ('plastic', 'Plastic'), ('food', 'Food'), ('other', 'Other')], max_length=50)),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SurplusListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('wood', 'Wood'), ('metal', 'Metal'), ('textiles', 'Textiles'), ('plastic', 'Plastic'), ('food', 'Food'), ('other', 'Other')], max_length=50)),
                ('monthly_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('approved', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.demandlisting')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('surplus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.surpluslisting')),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('surplus', 'demand')},
            },
        ),
    ]
