# Generated by Django 5.2.4 on 2026-01-17 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandlisting',
            options={'ordering': ['-created_on'], 'verbose_name': 'Demand Listing', 'verbose_name_plural': 'Demand Listings'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_on'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='surpluslisting',
            options={'ordering': ['-created_on'], 'verbose_name': 'Surplus Listing', 'verbose_name_plural': 'Surplus Listings'},
        ),
        migrations.RemoveField(
            model_name='demandlisting',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='demandlisting',
            name='org',
        ),
        migrations.AddField(
            model_name='demandlisting',
            name='intended_use',
            field=models.TextField(blank=True, help_text='Describe how the material will be used'),
        ),
        migrations.AddField(
            model_name='demandlisting',
            name='organisation',
            field=models.CharField(blank=True, help_text='Organisation or individual requesting material', max_length=150),
        ),
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this match'),
        ),
        migrations.AddField(
            model_name='surpluslisting',
            name='description',
            field=models.TextField(blank=True, help_text='Optional details about the material (condition, packaging, etc.)'),
        ),
        migrations.AddField(
            model_name='surpluslisting',
            name='is_food_safe',
            field=models.BooleanField(default=False, help_text='Only required if material type is food'),
        ),
        migrations.AlterField(
            model_name='demandlisting',
            name='approved',
            field=models.BooleanField(default=False, help_text='Admin approval before appearing publicly'),
        ),
        migrations.AlterField(
            model_name='demandlisting',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='demandlisting',
            name='material_wanted',
            field=models.CharField(choices=[('wood', 'Wood'), ('metal', 'Metal'), ('textiles', 'Textiles'), ('plastic', 'Plastic'), ('foam', 'Foam'), ('cardboard', 'Cardboard'), ('food', 'Food'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='demandlisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='directory.demandlisting'),
        ),
        migrations.AlterField(
            model_name='match',
            name='suggested_by',
            field=models.ForeignKey(blank=True, help_text='Admin or system user who suggested the match', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='surplus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='directory.surpluslisting'),
        ),
        migrations.AlterField(
            model_name='surpluslisting',
            name='approved',
            field=models.BooleanField(default=False, help_text='Admin approval before appearing publicly'),
        ),
        migrations.AlterField(
            model_name='surpluslisting',
            name='company',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='surpluslisting',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='surpluslisting',
            name='material_type',
            field=models.CharField(choices=[('wood', 'Wood'), ('metal', 'Metal'), ('textiles', 'Textiles'), ('plastic', 'Plastic'), ('foam', 'Foam'), ('cardboard', 'Cardboard'), ('food', 'Food'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='surpluslisting',
            name='monthly_volume',
            field=models.DecimalField(decimal_places=2, help_text='Estimated monthly surplus volume', max_digits=10),
        ),
        migrations.AlterField(
            model_name='surpluslisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
