# Generated by Django 5.2.4 on 2026-01-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_demandlisting_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandlisting',
            name='intended_use',
            field=models.TextField(blank=True, help_text='Describe how the material will be used', null=True),
        ),
        migrations.AlterField(
            model_name='demandlisting',
            name='organisation',
            field=models.CharField(blank=True, help_text='Organisation or individual requesting material', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this match', null=True),
        ),
    ]
